// Math class
document.write("<h1>Math class</h1>");
document.write("<p>Math.PI: " + Math.PI + "</p>");
document.write("<p>Math.E: " + Math.E + "</p>");
document.write("<p>Math.abs(-5): " + Math.abs(-5) + "</p>");
document.write("<p>Math.ceil(4.2): " + Math.ceil(4.2) + "</p>");
document.write("<p>Math.floor(4.2): " + Math.floor(4.2) + "</p>");
document.write("<p>Math.round(4.2): " + Math.round(4.2) + "</p>");
document.write("<p>Math.max(4, 2): " + Math.max(4, 2) + "</p>");
document.write("<p>Math.min(4, 2): " + Math.min(4, 2) + "</p>");
document.write("<p>Math.pow(4, 2): " + Math.pow(4, 2) + "</p>");
document.write("<p>Math.sqrt(4): " + Math.sqrt(4) + "</p>");
document.write("<p>Math.random(): " + Math.random() + "</p>");
document.write("<hr>");

// String class
document.write("<h1>String class</h1>");
let str = "Hello World!";
document.write("<p>str: " + str + "</p>");
document.write("<p>str.length: " + str.length + "</p>");
document.write("<p>str.charAt(0): " + str.charAt(0) + "</p>");
document.write("<p>str.charCodeAt(0): " + str.charCodeAt(0) + "</p>");
document.write("<p>str.concat(\" Goodbye!\"): " + str.concat(" Goodbye!") + "</p>");
document.write("<p>str.indexOf(\"o\"): " + str.indexOf("o") + "</p>");
document.write("<p>str.lastIndexOf(\"o\"): " + str.lastIndexOf("o") + "</p>");
document.write("<p>str.substring(0, 5): " + str.substring(0, 5) + "</p>");
document.write("<p>str.slice(0, 5): " + str.slice(0, 5) + "</p>");
document.write("<p>str.slice(-6, -1): " + str.slice(-6, -1) + "</p>");
document.write("<p>str.split(\" \"): " + str.split(" ") + "</p>");
document.write("<p>str.replace(\"Hello\", \"Goodbye\"): " + str.replace("Hello", "Goodbye") + "</p>");
document.write("<p>str.toUpperCase(): " + str.toUpperCase() + "</p>");
document.write("<p>str.toLowerCase(): " + str.toLowerCase() + "</p>");
document.write("<hr>");

// Date class
document.write("<h1>Date class</h1>");
let date = new Date();
document.write("<p>date: " + date + "</p>");
document.write("<p>date.getDate(): " + date.getDate() + "</p>");
document.write("<p>date.getDay(): " + date.getDay() + "</p>");
document.write("<p>date.getFullYear(): " + date.getFullYear() + "</p>");
document.write("<p>date.getHours(): " + date.getHours() + "</p>");
document.write("<p>date.getMilliseconds(): " + date.getMilliseconds() + "</p>");
document.write("<p>date.getMinutes(): " + date.getMinutes() + "</p>");
document.write("<p>date.getMonth(): " + date.getMonth() + "</p>");
document.write("<p>date.getSeconds(): " + date.getSeconds() + "</p>");
document.write("<p>date.getTime(): " + date.getTime() + "</p>");
document.write("<p>date.getTimezoneOffset(): " + date.getTimezoneOffset() + "</p>");
document.write("<p>date.getUTCDate(): " + date.getUTCDate() + "</p>");
document.write("<p>date.getUTCDay(): " + date.getUTCDay() + "</p>");
document.write("<p>date.getUTCFullYear(): " + date.getUTCFullYear() + "</p>");
document.write("<p>date.getUTCHours(): " + date.getUTCHours() + "</p>");
document.write("<p>date.getUTCMilliseconds(): " + date.getUTCMilliseconds() + "</p>");
document.write("<p>date.getUTCMinutes(): " + date.getUTCMinutes() + "</p>");
document.write("<p>date.getUTCMonth(): " + date.getUTCMonth() + "</p>");
document.write("<p>date.getUTCSeconds(): " + date.getUTCSeconds() + "</p>");
document.write("<p>date.now(): " + Date.now() + "</p>");
document.write("<p>date.parse(\"March 21, 2012\"): " + Date.parse("March 21, 2012") + "</p>");
document.write("<p>date.setDate(21): " + date.setDate(21) + "</p>");
document.write("<p>date.setFullYear(2012): " + date.setFullYear(2012) + "</p>");
document.write("<p>date.setHours(21): " + date.setHours(21) + "</p>");
document.write("<p>date.setMilliseconds(21): " + date.setMilliseconds(21) + "</p>");
document.write("<p>date.setMinutes(21): " + date.setMinutes(21) + "</p>");
document.write("<p>date.setMonth(21): " + date.setMonth(21) + "</p>");
document.write("<p>date.setSeconds(21): " + date.setSeconds(21) + "</p>");
document.write("<p>date.setTime(21): " + date.setTime(21) + "</p>");
document.write("<p>date.setUTCDate(21): " + date.setUTCDate(21) + "</p>");
document.write("<p>date.setUTCFullYear(2012): " + date.setUTCFullYear(2012) + "</p>");
document.write("<p>date.setUTCHours(21): " + date.setUTCHours(21) + "</p>");
document.write("<p>date.setUTCMilliseconds(21): " + date.setUTCMilliseconds(21) + "</p>");
document.write("<p>date.setUTCMinutes(21): " + date.setUTCMinutes(21) + "</p>");
document.write("<p>date.setUTCMonth(21): " + date.setUTCMonth(21) + "</p>");
document.write("<p>date.setUTCSeconds(21): " + date.setUTCSeconds(21) + "</p>");
document.write("<p>date.toDateString(): " + date.toDateString() + "</p>");
document.write("<p>date.toISOString(): " + date.toISOString() + "</p>");
document.write("<p>date.toJSON(): " + date.toJSON() + "</p>");
document.write("<p>date.toLocaleDateString(): " + date.toLocaleDateString() + "</p>");
document.write("<p>date.toLocaleString(): " + date.toLocaleString() + "</p>");
document.write("<p>date.toLocaleTimeString(): " + date.toLocaleTimeString() + "</p>");
document.write("<p>date.toString(): " + date.toString() + "</p>");
document.write("<p>date.toTimeString(): " + date.toTimeString() + "</p>");
document.write("<p>date.toUTCString(): " + date.toUTCString() + "</p>");
document.write("<hr>");

// Number class
document.write("<h1>Number class</h1>");
let num = 123.456;
document.write("<p>num: " + num + "</p>");
document.write("<p>num.toExponential(): " + num.toExponential() + "</p>");
document.write("<p>num.toFixed(): " + num.toFixed() + "</p>");
document.write("<p>num.toLocaleString(): " + num.toLocaleString() + "</p>");
document.write("<p>num.toPrecision(): " + num.toPrecision() + "</p>");
document.write("<p>num.toString(): " + num.toString() + "</p>");
document.write("<p>num.valueOf(): " + num.valueOf() + "</p>");
document.write("<hr>");